import { MonthlyMilestone } from "../types";

export const month4: MonthlyMilestone = {
  month: 4,
  title: "Month 4: The Internal Developer Platform (IDP)",
  description: "Moving from cluster administrator to platform product engineer. Building Go operators, Crossplane control planes, and Backstage Developer Portals.",
  largeProject: "Build an Internal Developer Portal (Backstage) where developers can click a button to provision a new microservice repository, fully wired with CI/CD schemas, and dynamically provisioned Postgres databases via Crossplane.",
  platformReview: "Evaluate the 'golden paths' provided to developers. Is cognitive load reduced?",
  securityReview: "Review Crossplane provider credentials and Backstage identity integration.",
  reliabilityReview: "Test the robustness of the custom K8s Operator under heavy churn.",
  finalAssessment: "Demonstrate a complete self-service workflow from an empty git repo to a deployed application with an on-prem DB backing it.",
  weeks: [
    {
      week: 7,
      title: "Golang for Platform Engineers",
      miniProject: "Write a complete CLI utility in Go that authenticates to the K8s API, queries all pods across all namespaces consuming > 500Mi RAM, and exports a CSV report.",
      incidentSimulation: "Your Go operator introduces a memory leak in the K8s API server by improperly caching watch events. Debug and use pprof to fix it.",
      knowledgeReview: ["Go concurrency (goroutines/channels)", "client-go library", "K8s Informers & Listers"],
      architectureReview: "Design the architecture of a custom K8s controller vs a webhook.",
      documentationAssignment: "Write the README for your Go CLI.",
      days: [
        {
          day: 43,
          title: "Go Fundamentals & client-go",
          topic: "Speaking to the API",
          objectives: ["Write idiomatic Go", "Understand K8s ClientConfig", "Query the API efficiently"],
          theory: "Bash and Python break at scale. Go is the language of cloud-native. To build Kubernetes tools, you must interact with the API natively via `client-go`.",
          practicalTasks: [
            "Set up a pristine Go workspace and initialize client-go.",
            "Write a script that lists all Pods natively in a specific namespace using `client-go` locally (via kubeconfig).",
            "Implement a typed Go channel deliberately to safely pass collected pod names between worker goroutines.",
            "Add intricate contextual timeouts explicitly utilizing `context.WithTimeout` preventing hanging Kubernetes API calls.",
            "Write exhaustive unit tests covering your Go CLI logic utilizing the powerful fake Kubernetes client (`fake.Clientset`).",
            "Handle API rate limiting gracefully by implementing exponential backoff routines for API queries.",
            "Compile an optimized statically linked Go binary explicitly targeting massive parallel execution without bloating file size."
          ],
          commands: ["go mod init", "go get k8s.io/client-go@latest", "go run main.go", "go test -v ./..."],
          deliverables: ["A heavily optimized binary capable of safely connecting to K8s.", "A fully covered unit test suite verifying client-go interactions.", "A detailed pprof memory analysis output."],
          expectedOutcome: "Can securely extend broad K8s functionality with compiled, type-safe tooling.",
          commonMistakes: ["Polling the API server sequentially in a `for` loop.", "Ignoring implicit Go error handling.", "Failing to close HTTP response bodies generated by API calls."],
          debuggingExercises: ["The client-go script panics with 'out of cluster' error. Fix the configuration loading logic.", "Simulate API latency. Debug why the goroutine locks indefinitely; pinpoint the missing context timeout."],
          productionMindset: "Treat the API server extremely nicely. Utilize caches (Informers) effectively to observe state changes."
        },
        {
          day: 44,
          title: "Writing Advanced Kubernetes Operators",
          topic: "Extending the Control Plane",
          objectives: ["Use Kubebuilder", "Define CRDs", "Write Reconcilers", "Handle Status updates"],
          theory: "Operators categorically encode complex human operational knowledge exclusively into software.",
          practicalTasks: [
            "Scaffold a brand new operator project thoroughly employing Kubebuilder.",
            "Define a dense CRD formally named `AppEnvironment` that spins up a Namespace, Deployment, and Service automatically.",
            "Write the comprehensive reconcile logic dynamically ensuring these 3 distinctly separate objects absolutely exist.",
            "Add a complex Status subresource iteratively to your CRD logically tracking the exact deployment progress uniquely.",
            "Implement a rigorous Validation Webhook strategically to reject incoming CRDs immediately if structurally invalid.",
            "Utilize controller-runtime's powerful `EnqueueRequestForOwner` accurately to rigidly watch child deployments.",
            "Add sophisticated logic strictly managing internal Finalizers."
          ],
          commands: ["kubebuilder init", "kubebuilder create api", "make manifests", "make run"],
          deliverables: ["A functional sophisticated Go custom controller.", "Extensively generated CRD yaml specifications.", "An automated integration testing suite validating reconcile logic."],
          expectedOutcome: "Profoundly transitioned from merely manipulating existing native K8s objects dynamically to explicitly creating entirely new APIs.",
          commonMistakes: ["Failing to handle complex 'requeue' logic properly within the controller loop.", "Not aggressively handling object Deletion procedures and vital Finalizers.", "Modifying the core Spec fields algorithmically instead of explicitly isolating data modification securely strictly within the distinct Status subresource."],
          debuggingExercises: ["A deleted custom resource gets brutally 'stuck' explicitly in a terminating state forever. Systematically fix the underlying Finalizer logic.", "The reconciler actively triggers an endless infinite loop. Diagnose the deeply embedded code flaw where updating the core Status triggers an implicit modification event."],
          productionMindset: "Operators constitute the ultimate pure expression of contemporary Platform Engineering."
        }
      ]
    },
    {
      week: 8,
      title: "Crossplane & Infrastructure as Data",
      miniProject: "Use Crossplane to create a custom API called CompanyDatabase.",
      incidentSimulation: "Crossplane loses connection to the infrastructure provider (Proxmox/AWS).",
      knowledgeReview: ["Crossplane Providers", "Compositions", "Composite Resource Definitions (XRDs)", "Crossplane vs Terraform"],
      architectureReview: "Debate the complexities of migrating from Terraform-driven CI/CD to Crossplane-driven declarative APIs.",
      documentationAssignment: "Write a provider diagram explaining how Crossplane creates external VMs.",
      days: [
        {
          day: 50,
          title: "Crossplane Fundamentals",
          topic: "The Universal Control Plane",
          objectives: ["Deploy Crossplane", "Configure Providers", "Package Compositions"],
          theory: "Crossplane lets you provision external infrastructure using native K8s YAML.",
          practicalTasks: [
            "Install Crossplane.",
            "Configure the Provider-Helm or Provider-Proxmox.",
            "Create a raw database instance using a Crossplane Managed Resource object.",
            "Write a Crossplane Composition that packages a Database, a Secret, and a Firewall rule together dynamically.",
            "Publish a custom Configuration package containing all XRD definitions directly to an OCI container registry.",
            "Set up complex Crossplane connection secret extraction algorithms storing generated DB credentials distinctly in Vault instantly.",
            "Build an internal developer portal form explicitly mapping inputs directly to the newly drafted Crossplane API."
          ],
          commands: ["kubectl crossplane install", "kubectl get crossplane", "kubectl describe composition"],
          deliverables: ["Infrastructure provisioned outside K8s.", "An OCI packaged composition layer.", "A connected Vault ingestion pipeline securely housing provisioned credentials exclusively."],
          expectedOutcome: "Understand the monumental industry shift thoroughly from pure Infrastructure-as-Code to true Infrastructure-as-Data paradigms.",
          commonMistakes: ["Giving frontend developers direct unadulterated access explicitly to primary Managed Resources intrinsically.", "Manually managing the exact same cloud resource jointly concurrently through both raw Terraform AND a running Crossplane operator concurrently.", "Failing to map essential patch sets perfectly between the parent XRD structure cleanly directly to the nested Composition resources dynamically."],
          debuggingExercises: ["A managed resource gets permanently stuck purely in a 'Syncing' state indefinitely. Extensively identify the explicitly missing core IAM/Secret permissions natively inside the embedded ProviderConfig.", "The Crossplane Composition refuses to generate output secrets properly. Inspect the rigid structural path definitions inside the patch arrays explicitly verifying data propagation logically."],
          productionMindset: "Unify the disparate API surface entirely. Developers categorically should not ever need to fundamentally learn native K8s YAML exclusively for pods and sprawling HCL templates strictly for databases."
        }
      ]
    }
  ]
};
